# Summary:
# This blueprint defines an automation for controlling a vacuum based on occupancy. 
# It includes the following inputs:
# - vacuum_entity: The vacuum to control.
# - leave_entities: People whose departure will start the vacuum.
# - arrival_entities: People whose arrival will stop the vacuum.
# - run_once: Option to run the automation only once per day.
# - before_time: Time before which the vacuum should not run.
# - run_periodically: Option to run the vacuum periodically if it hasn't been run in a specified number of days.
# - guest_mode: Option to allow the automation to trigger when guest mode is on.
#
# The automation triggers when people leave or arrive, and it includes conditions to respect guest mode, 
# run once per day, and not run before a specified time.

blueprint:
  name: Vacuum
  description: Controls a vacuum based on occupancy
  domain: automation
  input:
    vacuum_entity:
      name: Vacuum
      description: The vacuum to control
      selector:
        entity: 
          domain: 
            - vacuum
    leave_entities:
      name: Start when people leave
      description: Start the vacuum when these people leave
      selector:
        entity:
          domain:
            - person
          multiple: true
    arrival_entities:
      name: Stop when people arrive
      description: Stop the vacuum when these people arrive
      selector:
        entity:
          domain:
            - person
          multiple: true
    run_once:
      name: Run once per day
      description: Don't run the automation more than once per day
      selector:
        boolean: {}
      default: true
    before_time:
      name: Do not run before
      description: Do not run the vacuum before this time
      selector:
        time: {}
      default: '08:00:00'
    run_periodically:
      name: Run periodically
      description: Run the vacuum if it hasn't been run in x days. Set to 0 to disable
      selector:
        number:
          min: 0
          max: 14
          step: 1          
      default: 3
    guest_mode:
      name: Trigger while in guest mode
      description: If enabled, the automation can be triggered when guest mode is on
      selector:
        boolean: {}
      default: false

variables:
  guest_mode: !input guest_mode
  run_once: !input run_once
  run_periodically: !input run_periodically
  before_time: !input before_time
  vacuum_entity: !input vacuum_entity

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input arrival_entities
    to: 'home'
    id: 'someone_arrives'

  - platform: state
    entity_id: !input leave_entities
    from: 'home'
    to: 'not_home'
    id: 'someone_leaves'

  - platform: state
    entity_id: schedule.periodic_vacuum_check
    from: 'off'
    to: 'on'
    id: 'periodic_schedule'

condition:
  # guest mode constraint
  - condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - "{{ guest_mode == true }}"

  # run once constraint
  - condition: and
    conditions:
      - condition: template
        value_template: "{{ run_once == true }}"
      - condition: template
        value_template: "{{ not is_state_attr(vacuum_entity, 'status', 'cleaning') or (state_attr(vacuum_entity, 'last_changed') | as_datetime).date() != now().date() }}"

  # Disable before a certain time
  - condition: template
    value_template: "{{ now().strftime('%H:%M') >= before_time }}"

action:
  - choose:
    # Someone arrives
    - conditions:
        - condition: trigger
          id: 'someone_arrives'
      
      sequence:
        - if:
            - condition: state
              entity_id: !input vacuum_entity
              state: cleaning
          then:
            - service: vacuum.return_to_base
              target:
                entity_id: !input vacuum_entity
          else:
            - service: vacuum.stop
              target:
                entity_id: !input vacuum_entity

    # Start the vacuum
    - conditions:
        - condition: or
          conditions:
            - condition: trigger
              id: 'someone_leaves'
            - condition: and
              conditions:
                - condition: trigger
                  id: 'periodic_schedule'
                - condition: template
                  value_template: "{{ run_periodically > 0 }}"
                - condition: template
                  value_template: "{{ state_attr(this.entity_id, 'last_triggered') | default(today_at(), true) < (now() + timedelta(days=-3)) }}"

      sequence:
        - if:
            - condition: state
              entity_id: !input vacuum_entity
              state: docked
          then:
            - service: vacuum.start
              target: 
                entity_id: !input vacuum_entity
