blueprint:
  name: Vacuum
  description: Controls a vacuum based on occupancy
  domain: automation
  input:
    vacuum_entity:
      name: Vacuum
      description: The vacuum to control
      selector:
        entity: 
          domain: 
            - vacuum
    leave_entities:
      name: Start people
      description: Start when these people leave
      selector:
        entity:
          domain:
            - person
          multiple: true
    everyone_must_leave:
      name: Everyone must leave
      description: Start only if everyone has left
      selector:
        boolean: {}
      default: false
    arrival_entities:
      name: Stop people
      description: Stop when these people arrive
      selector:
        entity:
          domain:
            - person
          multiple: true
    run_once:
      name: Run once per day
      description: Don't run the automation more than once per day
      selector:
        boolean: {}
      default: true
    guest_mode:
      name: Trigger while in guest mode
      description: If enabled, the automation can be triggered when guest mode is on
      selector:
        boolean: {}
      default: false

variables:
  guest_mode: !input guest_mode
  run_once: !input run_once

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input arrival_entities
    to: 'home'
    id: 'someone_arrives'

  - platform: state
    entity_id: !input leave_entities
    from: 'home'
    to: 'not_home'
    id: 'someone_leaves'

condition:
  # guest mode constraint
  - condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - "{{ guest_mode == 'on' }}"

  # run once constraint
  - condition: or
    conditions:
      - condition: trigger
        id: 'someone_arrives'
      - "{{ run_once == 'off' }}"
      - condition: and
        conditions:
          - "{{ run_once == 'on' }}"
          - "{{ state_attr(this.entity_id, 'last_triggered') | default(today_at(), true) < today_at('06:00') }}"

action:
  - choose:
    # Someone arrives
    - conditions:
      - condition: trigger
        id: 'someone_arrives'
      
      sequence:
        - if:
            - condition: state
              entity_id: !input vacuum_entity
              state: cleaning
          then:
            - service: vacuum.return_to_base
              target:
                entity_id: !input vacuum_entity
          else:
            - service: vacuum.stop
              target:
                entity_id: !input vacuum_entity

    # Someone leaves
    - conditions:
      - condition: trigger
        id: 'someone_leaves'

      sequence:
        - if:
            - condition: state
              entity_id: !input vacuum_entity
              state: docked
          then:
            - service: vacuum.start
              target: 
                entity_id: !input vacuum_entity


